# Generated by Django 5.2.11 on 2026-02-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(blank=True, null=True)),
                ('gp_final', models.CharField(blank=True, max_length=255, null=True)),
                ('gp_unique', models.CharField(blank=True, max_length=255, null=True)),
                ('new_dist', models.CharField(blank=True, max_length=255, null=True)),
                ('district_u', models.CharField(blank=True, max_length=255, null=True)),
                ('uni_block', models.CharField(blank=True, max_length=255, null=True)),
                ('block_2020', models.CharField(blank=True, max_length=255, null=True)),
                ('sw_discharge_cumec', models.FloatField(blank=True, null=True)),
                ('sw_hrs', models.FloatField(blank=True, null=True)),
                ('sw_days', models.FloatField(blank=True, null=True)),
                ('canal_days', models.FloatField(blank=True, null=True)),
                ('canal_mcm', models.FloatField(blank=True, null=True)),
                ('tp_days', models.FloatField(blank=True, null=True)),
                ('tp_mcm', models.FloatField(blank=True, null=True)),
                ('total_human_population', models.FloatField(blank=True, null=True)),
                ('kharif_crop_category', models.CharField(blank=True, max_length=255, null=True)),
                ('kharif_crop_type', models.CharField(blank=True, max_length=255, null=True)),
                ('kharif_crop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('kharif_area_ha', models.FloatField(blank=True, null=True)),
                ('kharif_nir_mm', models.FloatField(blank=True, null=True)),
                ('kharif_action', models.CharField(blank=True, max_length=255, null=True)),
                ('rabi_crop_category', models.CharField(blank=True, max_length=255, null=True)),
                ('rabi_crop_type', models.CharField(blank=True, max_length=255, null=True)),
                ('rabi_crop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rabi_area_ha', models.FloatField(blank=True, null=True)),
                ('rabi_nir_mm', models.FloatField(blank=True, null=True)),
                ('rabi_action', models.CharField(blank=True, max_length=255, null=True)),
                ('zaid_crop_category', models.CharField(blank=True, max_length=255, null=True)),
                ('zaid_crop_type', models.CharField(blank=True, max_length=255, null=True)),
                ('zaid_crop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('zaid_area_ha', models.FloatField(blank=True, null=True)),
                ('zaid_nir_mm', models.FloatField(blank=True, null=True)),
                ('zaid_action', models.CharField(blank=True, max_length=255, null=True)),
                ('industry_name', models.CharField(blank=True, max_length=255, null=True)),
                ('industry_daily_water_req_l_day', models.FloatField(blank=True, null=True)),
                ('industry_no_of_days_in_use', models.FloatField(blank=True, null=True)),
                ('other_type_of_use', models.CharField(blank=True, max_length=255, null=True)),
                ('other_daily_water_req_l_day', models.FloatField(blank=True, null=True)),
                ('other_no_of_days_in_use', models.FloatField(blank=True, null=True)),
                ('bottom_of_unconfined_aquifer', models.FloatField(blank=True, null=True)),
                ('confined_aquifer_area', models.FloatField(blank=True, null=True)),
                ('pre_monsoon_piezometric_heads', models.FloatField(blank=True, null=True)),
                ('post_monsoon_piezometric_heads', models.FloatField(blank=True, null=True)),
                ('bottom_of_confining_layer', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
