# Generated by Django 5.2.11 on 2026-02-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='sw_irrigation_mcm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
