# Generated by Django 5.2.11 on 2026-02-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exceldata_sw_irrigation_mcm'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallInfiltrationFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(blank=True, null=True)),
                ('principal_aquifer', models.CharField(blank=True, max_length=255, null=True)),
                ('major_aquifer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('major_aquifer_name', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_percent', models.FloatField(blank=True, null=True)),
                ('minimum_percent', models.FloatField(blank=True, null=True)),
                ('maximum_percent', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
