# Generated by Django 5.2.11 on 2026-02-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_exceldata_yearly_recharges'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquiferData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('well_id', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('well_depth', models.FloatField(blank=True, null=True)),
                ('aquifer', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_2015', models.FloatField(blank=True, null=True)),
                ('pre_2016', models.FloatField(blank=True, null=True)),
                ('pre_2017', models.FloatField(blank=True, null=True)),
                ('pre_2018', models.FloatField(blank=True, null=True)),
                ('pre_2019', models.FloatField(blank=True, null=True)),
                ('pre_2020', models.FloatField(blank=True, null=True)),
                ('pre_2021', models.FloatField(blank=True, null=True)),
                ('pre_2022', models.FloatField(blank=True, null=True)),
                ('pre_2023', models.FloatField(blank=True, null=True)),
                ('pre_2024', models.FloatField(blank=True, null=True)),
                ('pst_2015', models.FloatField(blank=True, null=True)),
                ('pst_2016', models.FloatField(blank=True, null=True)),
                ('pst_2017', models.FloatField(blank=True, null=True)),
                ('pst_2018', models.FloatField(blank=True, null=True)),
                ('pst_2019', models.FloatField(blank=True, null=True)),
                ('pst_2020', models.FloatField(blank=True, null=True)),
                ('pst_2021', models.FloatField(blank=True, null=True)),
                ('pst_2022', models.FloatField(blank=True, null=True)),
                ('pst_2023', models.FloatField(blank=True, null=True)),
                ('pst_2024', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aquiferApi_aquiferdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'locationApi_block',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'locationApi_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GramPanchayat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'locationApi_grampanchayat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RainfallStation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rainfallApi_rainfallstation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationRainfall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('rainfall_mm', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rainfallApi_stationrainfall',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'locationApi_village',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('well_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_well', models.CharField(blank=True, max_length=255, null=True)),
                ('well_depth', models.FloatField(blank=True, null=True)),
                ('meta_date', models.DateField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('hardness', models.FloatField(blank=True, null=True)),
                ('alkalinity', models.FloatField(blank=True, null=True)),
                ('nitrate', models.FloatField(blank=True, null=True)),
                ('fluoride', models.FloatField(blank=True, null=True)),
                ('ec', models.FloatField(blank=True, null=True)),
                ('tds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'water_qualityApi_waterquality',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='exceldata',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='exceldata',
            table='api_exceldata',
        ),
    ]
