# Generated by Django 5.2.11 on 2026-02-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_aquiferdata_block_district_grampanchayat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='ars_annual_gw_recharge_ha_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ars_annual_no_of_fillings',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ars_department_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ars_estimated_cost_in_lakh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ars_financial_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ars_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ars_location_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ars_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ars_recharge_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ars_scheme_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ars_storage_capacity_ha_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ars_type_of_artificial_recharge_structure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ars_village_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ars_work_proposed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_funding_area_proposed_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_funding_department_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_funding_estimated_cost_in_lakh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_funding_financial_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_funding_scheme_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_funding_total_area_shifted_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_kharif_changed_area_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_kharif_changed_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_kharif_changed_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_kharif_changed_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_kharif_changed_water_req_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_kharif_original_area_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_kharif_original_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_kharif_original_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_kharif_original_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_kharif_original_water_req_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_rabi_changed_area_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_rabi_changed_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_rabi_changed_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_rabi_changed_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_rabi_changed_water_req_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_rabi_original_area_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_rabi_original_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_rabi_original_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_rabi_original_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_rabi_original_water_req_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_summer_changed_area_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_summer_changed_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_summer_changed_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_summer_changed_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_summer_changed_water_req_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_summer_original_area_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_summer_original_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_summer_original_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_summer_original_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='div_summer_original_water_req_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_funding_approximate_estimated_cost_in_lakh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_funding_area_proposed_for_drip_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_funding_department_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_funding_financial_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_funding_scheme_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_funding_total_area_proposed_for_drip_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_funding_total_area_under_conventional_irrigation_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_kharif_area_proposed_for_drip_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_kharif_area_under_conventional_irrigation_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_kharif_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_kharif_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_kharif_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_kharif_net_water_requirement_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_rabi_area_proposed_for_drip_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_rabi_area_under_conventional_irrigation_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_rabi_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_rabi_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_rabi_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_rabi_net_water_requirement_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_summer_area_proposed_for_drip_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_summer_area_under_conventional_irrigation_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_summer_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_summer_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_summer_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='drip_summer_net_water_requirement_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_funding_area_proposed_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_funding_department_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_funding_estimated_cost_in_lakh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_funding_financial_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_funding_scheme_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_funding_selected_measure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_funding_total_area_proposed_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_funding_total_area_selected_measure_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_kharif_area_proposed_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_kharif_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_kharif_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_kharif_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_kharif_measure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_kharif_water_req_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_kharif_water_saving_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_rabi_area_proposed_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_rabi_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_rabi_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_rabi_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_rabi_measure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_rabi_water_req_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_rabi_water_saving_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_summer_area_proposed_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_summer_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_summer_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_summer_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_summer_measure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_summer_water_req_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='inn_summer_water_saving_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_funding_approximate_estimated_cost_in_lakh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_funding_area_proposed_for_pipelines_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_funding_department_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_funding_financial_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_funding_scheme_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_funding_total_area_proposed_for_pipelines_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_funding_total_area_under_conventional_irrigation_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_kharif_area_proposed_for_pipelines_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_kharif_area_under_conventional_irrigation_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_kharif_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_kharif_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_kharif_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_kharif_net_water_requirement_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_rabi_area_proposed_for_pipelines_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_rabi_area_under_conventional_irrigation_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_rabi_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_rabi_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_rabi_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_rabi_net_water_requirement_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_summer_area_proposed_for_pipelines_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_summer_area_under_conventional_irrigation_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_summer_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_summer_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_summer_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pipeline_summer_net_water_requirement_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_funding_approximate_estimated_cost_in_lakh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_funding_area_proposed_for_sprinkler_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_funding_department_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_funding_financial_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_funding_scheme_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_funding_total_area_proposed_for_sprinkler_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_funding_total_area_under_conventional_irrigation_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_kharif_area_proposed_for_sprinkler_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_kharif_area_under_conventional_irrigation_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_kharif_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_kharif_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_kharif_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_kharif_net_water_requirement_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_rabi_area_proposed_for_sprinkler_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_rabi_area_under_conventional_irrigation_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_rabi_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_rabi_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_rabi_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_rabi_net_water_requirement_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_summer_area_proposed_for_sprinkler_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_summer_area_under_conventional_irrigation_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_summer_crop_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_summer_crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_summer_crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='sprinkler_summer_net_water_requirement_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='wcs_annual_no_of_fillings',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='wcs_department_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='wcs_effective_storage_available_ha_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='wcs_estimated_cost_in_lakh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='wcs_financial_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='wcs_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='wcs_location_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='wcs_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='wcs_scheme_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='wcs_storage_capacity_ha_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='wcs_type_of_water_conservation_structure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='wcs_village_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='wcs_work_proposed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
